name: deploy_to_dev

concurrency: 1

on:
 
  workflow_dispatch

env:
 
  DATABRICKS_HOST: ${{ vars.HOST }}
 
  DATABRICKS_TOKEN: ${{ secrets.TOKEN }}

jobs:
 
  deploy:
 
    environment: dev
 
    name: "Deploy bundle"
 
    runs-on: ubuntu-latest

    steps:
 
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - run: |
 
          databricks bundle validate -t "dev" --var="env=dev"
 
        env:
 
          DATABRICKS_HOST: ${{ vars.HOST }}
 
          DATABRICKS_TOKEN: ${{ secrets.TOKEN }}
 
          DATABRICKS_BUNDLE_ENV: dev

      - run: |
 
          databricks bundle deploy -t "dev" --var="env=dev"
 
        env:
 
          DATABRICKS_HOST: ${{ vars.HOST }}
 
          DATABRICKS_TOKEN: ${{ secrets.TOKEN }}
 
          DATABRICKS_BUNDLE_ENV: dev
 
 
