name: deploy_to_dev
 
concurrency: 1
 
on:

  workflow_dispatch
 
jobs:

  deploy:

    environment: dev

    name: "Deploy Databricks Bundle"

    runs-on: ubuntu-latest
 
    steps:

      - name: Checkout repository

        uses: actions/checkout@v3
 
      - name: Set up Databricks CLI

        uses: databricks/setup-cli@main
 
      - name: Configure Databricks credentials

        run: |

          mkdir -p ~/.databricks

          echo '{

            "host": "${{ vars.HOST }}",

            "token": "${{ secrets.TOKEN }}"

          }' > ~/.databricks/config
 
      - name: Validate Databricks Bundle

        run: databricks bundle validate

        env:

          DATABRICKS_BUNDLE_ENV: dev
 
      - name: Deploy Databricks Bundle

        run: databricks bundle deploy

        env:

          DATABRICKS_BUNDLE_ENV: dev

 
